Basic np.load implementation, falling back to NumPy
nv-legate/cunumeric pull request #1126
Opened 2024-02-21 01:05 UTC by manopapad

Mostly there to ensure that the NumPy ndarray coming out of `np.load` gets cast to a cuNumeric ndarray. As requested by ORNL.

2024-02-23 00:10 UTC, bryevdv requested changes
Probably needs docs in light of other PRs

2024-02-27 03:01 UTC, manopapad commented
I made a new `io.rst` and added `load`, but I'm getting an error when trying to build the docs locally:

```
/home/mpapadakis/a/cunumeric/docs/cunumeric/source/api/io.rst:document isn't included in any toctree
```

Any idea what I did wrong?

2024-02-27 17:44 UTC, bryevdv commented
You'd need to add `io` to a TOC somewhere so that it gets picked up, but I think given the current docs structure we don't want a new `io.rst` instead just an entry for `load` in existing `routines.rst`

2024-02-27 23:05 UTC, bryevdv approved these changes

2024-02-28 01:16 UTC, merged